MODEL_NAME: "llama32"
LLM_ENDPOINT: "http://localhost:8000"
BACKEND_ENDPOINT: ""
MLFLOW_TRACKING_URI: ""
MLFLOW_PROMPT_NAME: "summarization"
MLFLOW_PROMPT_VERSION: "latest"
image:
  name: "canopy-ui"
  tag: "simple-0.3"
